### ISSUE TITLE
Merge features to main repository

### ISSUE THREAD

**Issue by steffen-wilke** [sashahe/litiengine#121]
I've been lurking around your fork of the **LITIengine** and followed the development here.
As one of the authors of the engine, I think that there are some parts of this that might come in handy for the original engine.

Do you have any plans on creating PRs on the gurkenlabs/litiengine that contain your features? Otherwise, I'd just go ahead and cherry pick some of the commits that we think are useful for the project.

**Comment by sashahe** [comment]
Hi! Feel free to cherry pick :+1:

**Comment by steffen-wilke** [comment]
For now, I've merged most of the ability unit tests in #250.
Thank you very much 😄
